services:
  postgres:
    image: postgres:15
    container_name: finance-tracker-psql
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-tracker-network

  finance-tracker:
    build: .
    container_name: finance-tracker-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - finance-tracker-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  finance-tracker-network:
    driver: bridge